### PR TITLE
fix(build): copy the sidecar sources into the image build context

### PR DESCRIPTION
**Pull request by anikolaiev**
## Summary

`docker/Dockerfile` and `docker/Dockerfile.native` cannot build `main`.

The pom adds `sidecars/cedar/src/main/java` as a test source root (`build-helper-maven-plugin`, `add-cedar-sidecar-test-source`), and `.dockerignore` already whitelists `!sidecars/cedar/**`, but neither Dockerfile copies the directory into the build context. `mvn package -DskipTests` still compiles tests, so the build dies at `testCompile`:

```
ERROR .../VerifiedPermissionsIntegrationTest.java:[6,40] package io.github.hectorvent.floci.cedar does not exist
ERROR .../VerifiedPermissionsServiceTest.java:[39,23] cannot find symbol
  symbol: variable CedarSidecarServer
```

This fix copies `sidecars` alongside `src` in the two Dockerfiles that build from source.

`docker/Dockerfile.compat` and `docker/Dockerfile.native-package` consume a prebuilt native image rather than building from source, so they are unaffected — which is why `nightly.yml` has stayed green. `docker/Dockerfile` is referenced by `release.yml`, which runs on a tag, so the breakage would first show up at the next release cut.

Introduced by #3128, which added the sidecar and the `.dockerignore` entry.

## Type of change

- [x] Bug fix (`fix:`)
- [ ] New feature (`feat:`)
- [ ] Breaking change (`feat!:` or `fix!:`)
- [ ] Docs / chore

## AWS Compatibility

No emulated behaviour changes — this only restores the image build. The runtime image content is unchanged: the sidecar sources are a test source root, so nothing new is packaged into `quarkus-app/`.

## Checklist

- [x] New or updated integration test added — n/a, this is a build fix with no runtime behaviour
- [x] Commit messages follow [Conventional Commits](https://www.conventionalcommits.org/)

Verified by building `docker/Dockerfile` from `main` at `c1277941`: it fails with the error above before the change and succeeds after.

### CODE REVIEW

**Review by KenkoGeek — COMMENTED** [review]
Checked the two source-building Dockerfiles against the Maven setup and `.dockerignore`; this looks right to me.

`build-helper-maven-plugin` adds `sidecars/cedar/src/main/java` during `generate-test-sources`, and `-DskipTests` still runs test compilation. So once the verified-permissions tests reference `CedarSidecarServer`, a build context containing `src/` but not the Cedar sources cannot make it through `mvn package -DskipTests`.

Copying `sidecars/` in these two build stages fixes that without broadening the actual Docker context: `.dockerignore` already whitelists only `sidecars/cedar/**`. The runtime stages still copy only the packaged Quarkus/native artifacts, so this doesn't add the sidecar source tree to the final image.

I also checked the other Dockerfiles mentioned in the PR; the package/compat paths consume already-built artifacts and don't have the same source-compilation dependency. I don't see another change needed here.

**Comment by hectorvent** [comment]
Hi @anikolaiev,

I'd like to go over the implementation once more. We may need to move all sidecars into a dedicated repo, since sidecars shouldn't be injected directly into the container image.

Let's put together a plan and I'll share it once it's ready.

**Comment by chris-enroly** [comment]
Would it make sense to avoid compiling tests in the image builds instead of copying the Cedar sources into their build stages? `-DskipTests` skips test execution but still compiles test sources, while `-Dmaven.test.skip=true` skips test compilation too; applying it to both Dockerfiles lets the existing context omit sidecar sources while still compiling and packaging production code. I verified that the JVM image build succeeds with this change.

**Review by KenkoGeek — APPROVED** [review]
The required matrix is now fully green and the branch is CLEAN/MERGEABLE. I rechecked the same head against my earlier review: the build-context fix remains narrowly scoped to the source-building Dockerfiles, `.dockerignore` still limits the sidecar content to the intended Cedar sources, and the runtime images are unchanged. No remaining blocker from my side.

**Comment by pgermosen** [comment]
There's a new repo rule that blocks this regardless of the code review: main now requires every commit to be signed, and this branch's commit isn't. GitHub will refuse the merge outright once that's enforced, independent of review approval or CI, so this needs sorting before it can land.

Could you turn on commit signing (GPG or SSH, whichever you've got set up with GitHub) and re-push the commit?

**Comment by hectorvent** [comment]
@anikolaiev thanks for tracking this down, and for the clear before/after verification. Your diagnosis was right: the image builds break because `sidecars/cedar` is a test source root that neither Dockerfile copies. @chris-enroly's `-Dmaven.test.skip=true` idea was a sound alternative, too.

We fixed it at the root instead of in the build context. The sidecars no longer live in this repository:

- The Cedar sidecar moved to [floci-io/floci-sidecars](https://github.com/floci-io/floci-sidecars) and is published as `floci/floci-sidecar-cedar:1.1.0`.
- #3799 makes Floci pull that pinned image. It deletes `sidecars/cedar`, the build-helper test source root, the test-scoped cedar-java dependency and the `.dockerignore` entry, so there is nothing left for either Dockerfile to copy.

I'm closing this in favour of #3799. The `docker/Dockerfile` and `docker/Dockerfile.native` builds are fixed once that merges, so there's no need to re-push with signed commits here.
